### ISSUE TITLE
App crashes on ExchangeAPI Failures

### ISSUE THREAD

**Issue by aaur0** [gcarq/freqtrade#185]
The app has crashed a couple of times with the following error message:

`traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 63, in _process
    gen_pair_whitelist(_CONF['stake_currency'], topn = dynamic_whitelist) if dynamic_whitelist else None
  File "/freqtrade/freqtrade/main.py", line 35, in refresh_whitelist
    health = exchange.get_wallet_health()
  File "/freqtrade/freqtrade/exchange/__init__.py", line 185, in get_wallet_health
    return _API.get_wallet_health()
  File "/freqtrade/freqtrade/exchange/bittrex.py", line 174, in get_wallet_health
    raise OperationalException('{message}'.format(message=data['message']))
freqtrade.OperationalException: NO_API_RESPONSE
`

Based on the error message, it seems retrying will take care of intermittent API issues. We can consider retrying for read-only API calls.  I am thinking of adding re-try for methods in exchange/__init__.py using the retry modules. For example :

```python
@retry
def get_wallet_health() -> List[Dict]:
    return _API.get_wallet_health()
```

Let me know if the idea looks good. I'll send out a PR then.

**Comment by gcarq** [comment]
Did you pull the latest changes from develop? I've merged a PR an hour ago which should fix this: #183

**Comment by devalias** [comment]
Hi gcarq, I pulled the latest and still get:

Status: Got OperationalException:
Traceback (most recent call last):
  File "./freqtrade/main.py", line 70, in _process
    state_changed = create_trade(float(_CONF['stake_amount']))
  File "./freqtrade/main.py", line 195, in create_trade
    if exchange.get_balance(_CONF['stake_currency']) < stake_amount:
  File "/home/osboxes/freqtrade/freqtrade/exchange/__init__.py", line 127, in get_balance
    return _API.get_balance(currency)
  File "/home/osboxes/freqtrade/freqtrade/exchange/bittrex.py", line 72, in get_balance
    currency=currency))
freqtrade.OperationalException: NO_API_RESPONSE params=(BTC)

**Comment by gcarq** [comment]
I like the idea of the retry decorator but in this case it could fail more than once and it affects all bittrex endpoints. I'll write a testcase so that it is reproducible, it is strange that the exception is still reported as `freqtrade.OperationalException`, it should be a catched as `ContentDecodingError`:
```
freqtrade - WARNING - Got Got invalid response from bittrex params=(BTC_XRP) in _process(), retrying in 30 seconds...
```

**Comment by gcarq** [comment]
Is this still an issue? I didn't get this exception since commit bfb3e09
